import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * Generates src/data/enka-map.ts from Enka's published store files.
 *
 * Enka returns numeric avatar IDs and text-map hashes; turning those into names
 * and icons needs their store data. Rather than ship 420 KB of it (most of
 * which is other languages), this trims to exactly what a character chip needs.
 *
 * Re-run each patch: `pnpm build:data`. The script fails loudly rather than
 * writing a partial map, because a silently truncated map would show a
 * player's newest character as a blank chip.
 *
 *   source: https://github.com/EnkaNetwork/API-docs/tree/master/store
 */

const STORE = 'https://raw.githubusercontent.com/EnkaNetwork/API-docs/master/store';
const OUT = path.join(process.cwd(), 'src', 'data', 'enka-map.ts');

/** Enka's internal element names, mapped to the ones our tokens use. */
const ELEMENTS: Record<string, string> = {
  Fire: 'pyro',
  Water: 'hydro',
  Electric: 'electro',
  Ice: 'cryo',
  Wind: 'anemo',
  Rock: 'geo',
  Grass: 'dendro',
};

type EnkaCharacter = {
  Element?: string;
  NameTextMapHash?: number | string;
  SideIconName?: string;
  QualityType?: string;
  WeaponType?: string;
};

async function getJson<T>(url: string): Promise<T> {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url} returned ${response.status}`);
  return (await response.json()) as T;
}

async function main() {
  const [characters, loc] = await Promise.all([
    getJson<Record<string, EnkaCharacter>>(`${STORE}/characters.json`),
    getJson<Record<string, Record<string, string>>>(`${STORE}/loc.json`),
  ]);

  const english = loc.en;
  if (!english) throw new Error('loc.json has no "en" section');

  const entries: string[] = [];
  let skipped = 0;

  for (const [id, character] of Object.entries(characters)) {
    const name = english[String(character.NameTextMapHash ?? '')];
    const side = character.SideIconName;

    // The Traveler and a few internal entries have no name or icon. Skipping
    // them is correct; silently skipping a real character would not be, which
    // is why the count is reported.
    if (!name || !side) {
      skipped++;
      continue;
    }

    const element = ELEMENTS[character.Element ?? ''] ?? null;
    const rarity = character.QualityType === 'QUALITY_ORANGE' ? 5 : 4;
    // Enka serves art at /ui/<icon>.png; the portrait drops the "Side_".
    const icon = side.replace('_Side_', '_');

    entries.push(
      `  '${id}': { name: ${JSON.stringify(name)}, element: ${
        element ? `'${element}'` : 'null'
      }, rarity: ${rarity}, icon: '${icon}' },`,
    );
  }

  if (entries.length < 50) {
    throw new Error(`Only ${entries.length} characters mapped — the store format has changed`);
  }

  const file = `// Generated by scripts/build-enka-map.mts on ${new Date().toISOString().slice(0, 10)}.
// Do not edit by hand. Re-run \`pnpm build:data\` each patch.
//
// Source: https://github.com/EnkaNetwork/API-docs/tree/master/store

export type EnkaCharacterInfo = {
  name: string;
  /** One of our element tokens, or null for the Traveler-like entries. */
  element: string | null;
  rarity: 4 | 5;
  /** Art lives at https://enka.network/ui/<icon>.png */
  icon: string;
};

export const ENKA_CHARACTERS: Record<string, EnkaCharacterInfo> = {
${entries.sort().join('\n')}
};

/** Enka's asset CDN, which fan tools are expected to use (docs/DATA.md). */
export const ENKA_UI = 'https://enka.network/ui';

export function characterIconUrl(icon: string): string {
  return \`\${ENKA_UI}/\${icon}.png\`;
}

export function lookupCharacter(avatarId: number | string): EnkaCharacterInfo | null {
  return ENKA_CHARACTERS[String(avatarId)] ?? null;
}
`;

  await mkdir(path.dirname(OUT), { recursive: true });
  await writeFile(OUT, file, 'utf8');

  console.log(`Wrote ${entries.length} characters to src/data/enka-map.ts (skipped ${skipped}).`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
